#!/bin/bash                                                                     
# Name of your job
#SBATCH --job-name=svDriver
#SBATCH --partition=compute
#SBATCH --account=TG-MDE230014

# Specify the name of the output file. The %j specifies the job ID
#SBATCH --output=svDriver.o%j

# Specify the name of the error file. The %j specifies the job ID
#SBATCH --error=svDriver.e%j

# The walltime you require for your job
#SBATCH --time=48:00:00

# Job priority. Leave as normal for now
#SBATCH --qos=normal

# Number of nodes are you requesting for your job. You can have 24 processors per node
#SBATCH --nodes=1

# Amount of memory you require per node. The default is 4000 MB per node
#SBATCH --mem=16GB

# Number of processors per node
#SBATCH --ntasks-per-node=128


export OMP_NUM_THREADS=128

/home/schwarze/FEBio-FSG-build/bin/febio4 -i TAA_aneurysm.feb -nosplash -import ./FEFSG.o -dump -dump_stride=360
